# Generated by Django 3.2.5 on 2021-07-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210718_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='status',
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
